# Generated by Django 5.1.3 on 2024-11-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0002_alter_bug_options_alter_patch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='version',
            field=models.CharField(max_length=255, verbose_name='Version'),
        ),
    ]
